### ISSUE TITLE
Feature Request: Add Date_Added and Date_Modified columns

### ISSUE THREAD

**Issue by tonypnode** [kdorepos/gosplunk#3]
If I have time to do it, i'll add the functionality and submit PR...

To add on to Issue#1, It would be really cool if we could create a "Recent Activity" dashboard as the default view. Using date_added and date_modified (and maybe even username), we could present users with a dynamic view of newly added and recently updated content. 

I would understand if, from a splunk perspective, my vision might be turning Splunk into a web application, and might not be the right answer, but I think it might help accelerate adoption and provide a place for collaboration and learning.

**Comment by kdorepos** [comment]
Columns added in latest commit - dashboards will be reflected in latest release
